### ISSUE TITLE
【微信小程序】unocss 不支持直接使用自定义颜色

### ISSUE THREAD

**Issue by sendking** [Allen-1998/uni-vue3-vite-ts-pinia#56]
![image](https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/assets/12857833/3614b4cd-ce3d-4ebb-92c2-04b370619670)
![image](https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/assets/12857833/95e9cb07-3b78-4a16-899a-0ef97a90d949)

**Comment by Allen-1998** [comment]
参考 https://github.com/ttk-cli/uni-vue3-vite-ts-pinia/issues/35#issuecomment-1598867010
